version: "2"
services:
  web:
     build: .
     ports:
       - "8000:80"
     links:
       - db
     volumes:
       - ./app:/var/www/html

  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: terminator666
      MYSQL_USER: exaltedone
      MYSQL_PASSWORD: pumpkinpie332
      MYSQL_DATABASE: hiddenvault232
    ports:
      - "8889:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "8081:80"
    environment:
      MYSQL_USER: exaltedone
      MYSQL_PASSWORD: pumpkinpie332
      MYSQL_ROOT_PASSWORD: terminator666
