version: '3.7'
services:
  sample:
    container_name: hidden-games
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - '/home/joonasnivala/Documents/docker-1/02_bonus/dev_project_dockerfiles/react/app:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
