#!/bin/bash
#This pulls Hello World container. You can also just use run command, and it will download it from the docker repository.
#Run docker images to see images that are currently available locally.
docker pull hello-world
