#!/bin/bash
#First, we need to set our environment to the Char's unhospitable atmosphere:
eval $(docker-machine env Char)`
#To get the overlord's image to Char, run:
docker pull nginx
#To add the container that holds the overlord, you have now your container set as 192.168.x.x, and all your docker commands point to Char.
#-p or publish 192.168.1.100:8080:80 	Map TCP port 80 in the container to port 8080 on the Docker host for connections to host IP 192.168.1.100.
#--restart unless-stopped will restart the container unless specifically stopped. https://codeburst.io/how-to-start-docker-containers-automatically-ec0545c392e4
#--name to name the container
#Example:
#docker run --publish :8080 --detach --name bb bulletinboard:1.0
docker run --name overlord --restart unless-stopped --publish 5000:80 -d nginx:latest
#We use 0.0.0.0 since our environment is now set to 192.168.x.x, which is the planetary position of Char. We're not in Texas anymore. 
