#!/bin/bash
#From the shell of a debiancontainer, install via the container’s package manager
#everything you need to compile C source code and push it onto a git repo
#(ofcourse, make sure before that the package manager and the packages already in the
#container are updated). For this exercise, you should only specify the commands
#to be run directly in the container.
#First I ran the command to install a debian
#docker run -it debian /bin/bash
#Then update container
apt update -y
#Then get necessary files:
apt install build-essential git
