#!/bin/bash
#Launch a mysql container as a background task. It should be able to restart on its
#own in case of error, and the root password of the database should be Kerrigan.
#You will also make sure that the database is stored in the hatchery volume, that
#the container directly creates a database named zerglings, and that the container
#itself is named spawning-pool
##
#Assign name spawing-pool for the mysql container.
#set --restart on-failure
#You can use --volume to designate already created volume of hatchery.
#Add root password with --env option. Every --env variable needs to be set seperately.
#Use -d  mysql:latest to get the latest version and start in the background.
#docker exec -it spawning-pool mysql -uroot -p test that container has indeed all installed with password Kerrigan.
docker run --name spawning-pool --restart on-failure --volume hatchery:/var/lib/mysql --env MYSQL_ROOT_PASSWORD=Kerrigan --env MYSQL_DATABASE=zerglings -d mysql:latest
