#!/bin/bash
#Turn Aiur into a slave of the local swarm in which Char is leader (the command to
#take control of Aiur is not requested).
#First ssh to Aiur.
docker-machine ssh Aiur
#Then run the command that we previously received.
docker swarm join --token $(docker swarm join-token worker -q) $(docker-machine ip Char):2377
#Then exit and switch env variables to Char. run docker node ls to see that Aiur is correctly added.
